{% set name = "pybasemkit" %}
{% set version = "0.0.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybasemkit-{{ version }}.tar.gz
  sha256: 310ecec5962c3e4b1311b9c9c969789d4d1ceb08688311de2e0fc04754502eee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dacite >=1.9.2
    - dataclasses-json >=0.6.7
    - pyyaml >=6.0.2
    - shutup >=0.2.0

test:
  imports:
    - basemkit
  commands:
    # Disabling pip check for now due to issues with upstream dacite 1.9.2 release mismatch
    # (see https://github.com/konradhalas/dacite/commit/daad7e4a15569321d3cf118f8083a71a65d7e044)
    # We can plan to re-enable the check once dacite corrects release mismatch issues
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WolfgangFahl/pybasemkit
  summary: 'Python base module kit: YAML/JSON I/O, structured logging, CLI tooling, shell execution, and pydevd remote debug support.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
